name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Podman
        run: sudo apt-get update && sudo apt-get install -y podman
      - name: Run container-based install test
        run: scripts/test-install.sh

  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run local install test
        run: scripts/test-install.sh --local
      - name: Check Brewfile
        run: brew bundle check --file Brewfile